In [1]:
from sportsref.baseball import League, Season

im calling bref now

In [2]:
league = League()

In [3]:
league

In [4]:
league.wins()

,Year,G,ARI,ATL,BLA,BAL,BOS,CHC,CHW,CIN,...,PHI,PIT,SDP,SFG,SEA,STL,TBR,TEX,TOR,WSN
0,2019,162,85.0,97,NaN,54,84,84,72,75,...,81,69,70.0,77,68.0,91,96.0,78.0,67.0,93.0
1,2018,163,82.0,90,NaN,47,108,95,62,67,...,80,82,66.0,73,89.0,88,90.0,67.0,73.0,82.0
2,2017,162,93.0,72,NaN,75,93,92,67,68,...,66,75,71.0,64,78.0,83,80.0,78.0,76.0,97.0
3,2016,162,69.0,68,NaN,89,93,103,78,68,...,71,78,68.0,87,86.0,86,68.0,95.0,89.0,95.0
4,2015,162,79.0,67,NaN,81,78,97,76,64,...,63,98,74.0,84,76.0,100,80.0,88.0,93.0,83.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,1905,154,NaN,51,NaN,54,78,92,92,79,...,83,96,NaN,105,NaN,58,NaN,NaN,NaN,NaN
119,1904,154,NaN,55,NaN,65,95,93,89,88,...,52,87,NaN,106,NaN,75,NaN,NaN,NaN,NaN
120,1903,140,NaN,58,NaN,65,91,82,60,74,...,49,91,NaN,84,NaN,43,NaN,NaN,NaN,NaN
121,1902,140,NaN,73,50.0,78,77,68,74,70,...,56,103,NaN,48,NaN,56,NaN,NaN,NaN,NaN
122,1901,140,NaN,69,68.0,48,79,53,83,52,...,83,90,NaN,52,NaN,76,NaN,NaN,NaN,NaN

In [5]:
league.stats(table="teams_standard_pitching", stats_type="pitch")

,Year,Tms,#P,PAge,R/G,ERA,G,GF,CG,SHO,...,BF,ERA+,WHIP,BAbip,H9,HR9,BB9,SO9,SO/W,E
0,2019,30,831,28.4,4.83,4.51,4858,0.99,0.01,0.01,...,38.39,NaN,1.334,0.298,8.7,1.4,3.3,8.9,2.69,0.60
1,2018,30,799,28.4,4.45,4.15,4862,0.99,0.01,0.00,...,38.08,NaN,1.304,0.295,8.5,1.2,3.2,8.5,2.63,0.57
2,2017,30,755,28.5,4.65,4.36,4860,0.99,0.01,0.01,...,38.13,NaN,1.342,0.300,8.8,1.3,3.3,8.3,2.53,0.58
3,2016,30,742,28.3,4.48,4.19,4856,0.98,0.02,0.01,...,38.01,NaN,1.325,0.300,8.8,1.2,3.1,8.1,2.58,0.58
4,2015,30,735,28.4,4.25,3.96,4858,0.98,0.02,0.01,...,37.80,NaN,1.294,0.299,8.7,1.0,2.9,7.8,2.66,0.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,1875,13,42,24.3,6.14,2.23,690,0.10,0.90,0.07,...,39.25,NaN,1.141,NaN,9.9,0.1,0.4,1.0,2.71,6.96
150,1874,8,17,24.7,7.48,2.19,464,0.05,0.95,0.03,...,41.69,NaN,1.310,NaN,11.3,0.1,0.5,0.8,1.50,8.14
151,1873,9,25,21.3,8.99,3.40,398,0.09,0.91,0.02,...,43.45,NaN,1.468,NaN,12.4,0.1,0.8,0.7,0.83,8.02
152,1872,11,21,21.1,9.26,3.66,366,0.11,0.89,0.03,...,43.52,NaN,1.439,NaN,12.2,0.1,0.7,0.7,1.01,7.50
153,1871,9,19,24.6,10.47,4.22,254,0.09,0.91,0.02,...,44.15,NaN,1.553,NaN,12.4,0.2,1.6,0.7,0.45,7.61

In [6]:
mlb2019 = Season(2019)

In [13]:
mlb2019.standings("expanded_standings_overall")

,Rk,Tm,Lg,G,W,L,W-L%,Strk,R,RA,...,Road,ExInn,1Run,vRHP,vLHP,≥.500,<.500,last10,last20,last30
0,1.0,y-HOU,AL,162.0,107,55,0.660,W 3,5.7,4.0,...,47-34,10-4,24-19,69-44,38-11,35-28,72-27,8-2,15-5,22-8
1,2.0,y-LAD,NL,162.0,106,56,0.654,W 7,5.5,3.8,...,47-34,6-4,27-22,76-34,30-22,45-32,61-24,8-2,14-6,20-10
2,3.0,y-NYY,AL,162.0,103,59,0.636,L 2,5.8,4.6,...,46-35,7-4,18-19,70-41,33-18,43-32,60-27,4-6,11-9,18-12
3,4.0,y-MIN,AL,162.0,101,61,0.624,L 1,5.8,4.7,...,55-26,5-7,23-12,79-44,22-17,32-37,69-24,8-2,13-7,20-10
4,5.0,y-ATL,NL,162.0,97,65,0.599,L 3,5.3,4.6,...,47-34,11-6,28-16,74-51,23-14,52-43,45-22,4-6,9-11,17-13
5,6.0,w-OAK,AL,162.0,97,65,0.599,L 1,5.2,4.2,...,45-36,6-9,27-22,62-51,35-14,35-27,62-38,6-4,14-6,20-10
6,7.0,w-TBR,AL,162.0,96,66,0.593,L 2,4.7,4.0,...,48-33,11-8,23-16,64-41,32-25,38-35,58-31,7-3,13-7,20-10
7,8.0,w-WSN,NL,162.0,93,69,0.574,W 8,5.4,4.5,...,43-38,4-6,17-21,69-52,24-17,48-48,45-21,9-1,14-6,19-11
8,9.0,CLE,AL,162.0,93,69,0.574,L 5,4.7,4.1,...,44-37,6-7,15-16,60-47,33-22,25-39,68-30,4-6,11-9,16-14
9,10.0,y-STL,NL,162.0,91,71,0.562,W 1,4.7,4.1,...,41-40,8-4,25-22,73-55,18-16,42-42,49-29,6-4,11-9,18-12
10,11.0,w-MIL,NL,162.0,89,73,0.549,L 3,4.7,4.7,...,40-41,7-8,27-18,64-49,25-24,48-40,41-33,7-3,15-5,22-8
11,12.0,NYM,NL,162.0,86,76,0.531,W 3,4.9,4.5,...,38-43,7-9,24-23,68-53,18-23,47-55,39-21,7-3,14-6,19-11
12,13.0,ARI,NL,162.0,85,77,0.525,W 5,5.0,4.6,...,41-40,9-9,24-26,60-58,25-19,35-40,50-37,8-2,10-10,19-11
13,14.0,BOS,AL,162.0,84,78,0.518,W 1,5.6,5.1,...,46-35,9-8,23-22,60-48,24-30,28-45,56-33,4-6,8-12,14-16
14,15.0,CHC,NL,162.0,84,78,0.518,L 1,5.0,4.4,...,33-48,4-9,19-27,70-60,14-18,39-45,45-33,2-8,8-12,13-17
15,16.0,PHI,NL,162.0,81,81,0.500,L 1,4.8,4.9,...,36-45,7-6,20-20,63-56,18-25,48-52,33-29,3-7,7-13,12-18
16,17.0,TEX,AL,162.0,78,84,0.481,W 2,5.0,5.4,...,33-48,7-6,25-21,52-52,26-32,31-53,47-31,4-6,9-11,14-16
17,18.0,SFG,NL,162.0,77,85,0.475,L 3,4.2,4.8,...,42-39,13-3,38-16,57-56,20-29,42-55,35-30,3-7,8-12,12-18
18,19.0,CIN,NL,162.0,75,87,0.463,W 2,4.3,4.4,...,34-47,7-8,24-33,58-64,17-23,46-60,29-27,4-6,9-11,12-18
19,20.0,CHW,AL,161.0,72,89,0.447,W 1,4.4,5.2,...,33-48,4-4,14-18,44-62,28-27,35-53,37-36,7-3,10-10,12-18
20,21.0,LAA,AL,162.0,72,90,0.444,L 3,4.7,5.4,...,34-47,3-7,18-22,49-60,23-30,29-55,43-35,3-7,6-14,9-21
21,22.0,COL,NL,162.0,71,91,0.438,W 3,5.2,5.9,...,28-53,10-6,22-21,46-55,25-36,38-60,33-31,5-5,11-9,12-18
22,23.0,SDP,NL,162.0,70,92,0.432,L 6,4.2,4.9,...,34-47,5-7,26-24,56-70,14-22,40-53,30-39,1-9,4-16,9-21
23,24.0,PIT,NL,162.0,69,93,0.426,L 2,4.7,5.6,...,34-47,7-11,19-25,53-66,16-27,30-72,39-21,4-6,7-13,13-17
24,25.0,SEA,AL,162.0,68,94,0.420,W 1,4.7,5.5,...,33-48,9-4,23-26,52-58,16-36,22-59,46-35,4-6,10-10,12-18
25,26.0,TOR,AL,162.0,67,95,0.414,W 2,4.5,5.1,...,32-49,7-8,18-23,43-65,24-30,35-58,32-37,6-4,12-8,14-16
26,27.0,KCR,AL,162.0,59,103,0.364,W 1,4.3,5.4,...,28-53,4-9,15-25,43-76,16-27,28-60,31-43,3-7,7-13,13-17
27,28.0,MIA,NL,162.0,57,105,0.352,W 1,3.8,5.0,...,27-54,7-9,16-28,39-81,18-24,38-83,19-22,4-6,6-14,10-20
28,29.0,BAL,AL,162.0,54,108,0.333,L 1,4.5,6.1,...,29-52,2-8,11-22,33-67,21-41,26-67,28-41,5-5,8-12,10-20
29,30.0,DET,AL,161.0,47,114,0.292,L 1,3.6,5.7,...,25-55,6-10,14-22,34-90,13-24,19-65,28-49,2-8,5-15,8-22
30,NaN,Avg,NaN,NaN,80,80,0.500,NaN,4.8,4.8,...,38-42,6-6,21-21,58-56,22-24,36-49,44-31,5-5,9-10,14-15

In [17]:
bat2019 = mlb2019.standard_stats('players_standard_batting')

In [18]:
bat2019.shape

(1555, 30)

In [19]:
bat2019

,Rk,Name,Age,Tm,Lg,G,PA,AB,R,H,...,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,Pos Summary
0,1.0,Fernando Abad*,33.0,SFG,NL,18,0,0,0,0,...,NaN,NaN,NaN,0,0,0,0,0,0,1
1,2.0,Jose Abreu,32.0,CHW,AL,159,693,634,85,180,...,0.503,0.834,119.0,319,24,13,0,10,4,*3D
2,3.0,Ronald Acuna Jr.,21.0,ATL,NL,156,715,626,127,175,...,0.518,0.883,122.0,324,8,9,0,1,4,*879
3,4.0,Jason Adam,27.0,TOR,AL,3,0,0,0,0,...,NaN,NaN,NaN,0,0,0,0,0,0,1
4,5.0,Cristhian Adames#,27.0,SFG,NL,10,24,22,1,7,...,0.364,0.739,100.0,8,0,0,0,0,0,/45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,1551.0,Ryan Zimmerman,34.0,WSN,NL,52,190,171,20,44,...,0.415,0.736,86.0,71,4,0,0,2,0,3/D
1613,1552.0,Jordan Zimmermann,33.0,DET,AL,1,2,2,0,0,...,0.000,0.000,-100.0,0,0,0,0,0,0,1
1614,1553.0,Ben Zobrist#,38.0,CHC,NL,47,176,150,24,39,...,0.313,0.671,77.0,47,6,1,0,2,0,49/7D16
1615,1554.0,Mike Zunino,28.0,TBR,AL,90,289,266,30,44,...,0.312,0.544,44.0,83,4,3,0,0,0,2
1616,NaN,LgAvg per 600 PA,NaN,NaN,NaN,201,600,536,75,134,...,0.432,0.752,NaN,232,11,6,2,4,2,NaN

In [25]:
bat2019.query("PA > 100").sort_values("SLG", ascending=False).head(20).Tm.value_counts()

HOU    3
LAD    2
MIN    2
PHI    2
COL    2
NYM    1
CIN    1
ARI    1
CHC    1
TEX    1
SDP    1
WSN    1
MIL    1
LAA    1
Name: Tm, dtype: int64