In [2]:
from sportsref.baseball import League, Season

In [21]:
szn = Season(1985)

In [22]:
szn.batting("cumulative").get_df("players_cumulative_batting")

Available tables: ['players_cumulative_batting']

,Rk,Name,Age,Yrs,G,PA,AB,R,H,2B,...,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB
0,1,Don Aase,30,8,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
1,2,Johnny Abrego,22,1,6,9,9,0,0,0,...,0.000,0.000,0.000,-100.0,0,0,0,0,0,0
2,3,Jim Acker,26,3,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,0,0,0,0,0,0
3,4,Ricky Adams,26,3,120,269,247,35,53,5,...,0.260,0.291,0.551,55.0,72,5,5,7,0,3
4,5,Jim Adduci*,25,1,10,21,20,0,1,0,...,0.095,0.050,0.145,-59.0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,1021,Joel Youngblood,33,10,1083,3499,3143,399,843,156,...,0.333,0.398,0.731,106.0,1252,64,31,14,25,28
1021,1022,Robin Yount,29,12,1671,7148,6515,961,1856,349,...,0.331,0.428,0.759,113.0,2787,128,16,74,70,31
1022,1023,Pat Zachry,33,10,293,367,318,9,36,0,...,0.150,0.113,0.263,-25.0,36,11,0,33,2,0
1023,1024,Geoff Zahn*,39,13,48,53,43,3,6,0,...,0.140,0.140,0.279,-22.0,6,1,0,10,0,0
1024,1025,Paul Zuvella,26,4,97,246,221,18,53,9,...,0.306,0.290,0.595,64.0,64,3,1,4,0,1

In [31]:
szn.other('births').get_df('misc_pitching').query("Birthdate == 'Jan 18'")

Available tables: ['misc_batting', 'misc_pitching']

Empty DataFrame
Columns: [Rk, Name, Yrs, From, To, ASG, WAR, W, L, W-L%, ERA, G, GS, GF, CG, SHO, SV, IP, H, R, ER, HR, BB, IBB, SO, HBP, BK, WP, BF, WHIP, Birthdate, Birthplace, Tms]
Index: []

[0 rows x 33 columns]

In [24]:
szn.other('deaths').get_df('misc_manage')

Available tables: ['misc_batting', 'misc_pitching', 'misc_manage']

,Rk,Mgr,Yrs,From,To,W,L,W-L%,Ties,G>.500,G,BestFin,WrstFin,AvRk,Ejections,Date of Death,Died
0,1,Ossie Bluege,5,1943,1947,375,394,0.488,3,-19,772,2,8,4.6,4,Oct 14,"Edina, MN, United States"
1,2,Burleigh Grimes HOF,2,1937,1938,131,171,0.434,4,-40,306,6,7,6.5,15,Dec 6,"Clear Lake, WI, United States"
2,3,Bob Scheffing,6,1957,1963,418,427,0.495,4,-9,849,2,8,5.1,10,Oct 26,"Phoenix, AZ, United States"

In [25]:
szn.minor_leagues().get_df('league_pitching')

Available tables: ['league_batting', 'league_pitching', 'league_fielding', 'lg_history']

,Rk,Lg,Lev,Tms,PAge,R/G,W,L,W-L%,ERA,...,HBP,BK,WP,BF,WHIP,H9,HR9,BB9,SO9,SO/W
0,1.0,American League,Major League,14.0,28.4,4.56,1131.0,1131.0,0.5,4.15,...,419.0,107.0,639.0,86457.0,1.370,9.0,1.0,3.3,5.3,1.58
1,2.0,National League,Major League,12.0,28.2,4.07,970.0,970.0,0.5,3.59,...,280.0,120.0,501.0,73863.0,1.314,8.5,0.7,3.3,5.5,1.67
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,American Association,AAA,8.0,26.4,4.27,567.0,567.0,0.5,3.84,...,246.0,131.0,420.0,NaN,1.377,8.6,0.7,3.7,5.6,1.50
4,4.0,International League,AAA,8.0,25.9,4.24,557.0,557.0,0.5,3.75,...,223.0,74.0,425.0,NaN,1.378,8.7,0.8,3.7,5.2,1.41
5,5.0,Mexican League,AAA,16.0,NaN,5.09,1015.0,1015.0,0.5,4.70,...,598.0,46.0,835.0,NaN,1.567,10.2,0.9,3.9,4.9,1.25
6,6.0,Pacific Coast League,AAA,10.0,25.7,4.67,711.0,711.0,0.5,4.17,...,261.0,137.0,561.0,NaN,1.465,9.4,0.7,3.8,5.9,1.58
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,7.0,Eastern League,AA,8.0,23.3,4.23,554.0,554.0,0.5,3.74,...,283.0,90.0,419.0,NaN,1.402,8.5,0.5,4.1,5.6,1.36
9,8.0,Southern League,AA,10.0,23.9,4.70,717.0,717.0,0.5,4.17,...,397.0,106.0,679.0,NaN,1.477,9.0,0.8,4.2,5.2,1.22
10,9.0,Texas League,AA,8.0,23.3,4.76,542.0,542.0,0.5,4.08,...,246.0,138.0,532.0,NaN,1.458,9.2,0.7,4.0,6.0,1.52
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,10.0,California League,A,9.0,22.6,4.98,651.0,651.0,0.5,4.30,...,406.0,89.0,782.0,NaN,1.566,9.3,0.5,4.8,6.4,1.31
13,11.0,Carolina League,A,8.0,22.0,4.12,552.0,552.0,0.5,3.46,...,298.0,121.0,568.0,NaN,1.368,8.2,0.5,4.1,7.0,1.71
14,12.0,Florida State League,A,12.0,22.5,3.95,835.0,835.0,0.5,3.30,...,354.0,228.0,876.0,NaN,1.375,8.3,0.3,4.0,5.8,1.43
15,13.0,Midwest League,A,12.0,21.9,4.49,833.0,833.0,0.5,3.73,...,511.0,136.0,930.0,NaN,1.386,8.5,0.6,4.0,6.8,1.69
16,14.0,South Atlantic League,A,10.0,21.2,4.79,684.0,684.0,0.5,3.90,...,425.0,128.0,972.0,NaN,1.445,8.6,0.6,4.4,7.1,1.60
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,15.0,New York-Pennsylvania League,Short-Season A,12.0,20.8,4.41,463.0,463.0,0.5,3.53,...,285.0,66.0,655.0,NaN,1.386,7.9,0.5,4.6,7.6,1.67
19,16.0,Northwest League,Short-Season A,8.0,21.1,5.35,296.0,296.0,0.5,4.15,...,233.0,29.0,485.0,NaN,1.511,9.0,0.6,4.6,7.5,1.64
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,17.0,Appalachian League,Rookie,7.0,19.9,4.94,243.0,243.0,0.5,4.63,...,120.0,43.0,357.0,NaN,1.505,8.7,0.6,4.8,6.6,1.36
22,18.0,Gulf Coast League,Rookie,10.0,20.2,4.44,308.0,308.0,0.5,3.08,...,254.0,86.0,465.0,NaN,1.331,8.3,0.2,3.7,6.9,1.88
23,19.0,Pioneer League,Rookie,8.0,21.3,5.67,276.0,276.0,0.5,4.63,...,164.0,73.0,451.0,NaN,1.584,9.8,0.4,4.4,7.2,1.62
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,20.0,Cuban National Series,Foreign,18.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,21.0,Japan Central League,Foreign,6.0,26.7,4.66,362.0,362.0,0.5,4.28,...,162.0,13.0,117.0,29959.0,1.420,9.3,1.2,3.5,5.4,1.55
27,22.0,Japan Pacific League,Foreign,6.0,27.5,5.19,367.0,367.0,0.5,4.68,...,255.0,13.0,110.0,30108.0,1.444,9.3,1.4,3.7,4.8,1.30
28,23.0,Korean Baseball Organization,Foreign,6.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,24.0,Colombian Winter League,Winter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,25.0,Dominican Winter League,Winter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,26.0,Mexican Pacific Winter League,Winter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,27.0,Puerto Rican Winter League,Winter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,28.0,Venezuelan Winter League,Winter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,29.0,Dominican Summer League,Foreign Rookie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,30.0,Arizona Instructional League,Winter Rookie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,31.0,Florida Instructional League,Winter Rookie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN